[audio]
sample_rate = 44100  # default 44100
channels = 1         # 1 or 2
duration = 0.33		 # in seconds

[output]
mode = "file"		 # file or stream(not implemented yet)
command = "afplay"   # default: afplay for file mode
args = ["-v", "0.3"] # volume to 0.3

[notes]
# octave 3
z = "C3"
x = "D3"
c = "E3"
v = "F3"
b = "G3"
n = "A3"
m = "B3"
# octave 4
a = "C4"
s = "D4"
d = "E4"
f = "F4"
g = "G4"
h = "A4"
j = "B4"
# octave 5
q = "C5"
w = "D5"
e = "E5"
r = "F5"
t = "G5"
y = "A5"
u = "B5"

[keymap]
quit = 3 # Ctrl-C code
stop = "p"
